# Generated by Django 5.0.3 on 2024-03-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date_time', models.DateTimeField()),
                ('no_of_people', models.IntegerField()),
                ('special_request', models.TextField()),
            ],
        ),
    ]
